import {connectionsPanel} from './connections.js';
import {createStockPanel} from './vids-stock.js?v=2';
import {uid,esc,clone,total,dimensions,sceneStart,layer,scene,blank,layerStyle,compile,templates,applyTemplate,parseSRT,captionLayers,toSRT} from './vids-core.js';

import {voiceWorkspace} from './vids-voices.js';
import {recordMedia} from './vids-recording.js';
import {editorExtras} from './vids-extras.js';

const $=s=>document.querySelector(s), app=$('#app'), modal=$('#modal');
const paths={plus:'M12 5v14M5 12h14',play:'M8 5l11 7-11 7z',pause:'M8 5v14M16 5v14',video:'M3 5h18v14H3zM8 2v6M16 2v6M3 9h18M10 12l5 2-5 3z',image:'M3 3h18v18H3zM3 17l6-6 4 4 3-3 5 5M15 7h.01',person:'M8 6a4 4 0 1 0 8 0 4 4 0 1 0-8 0M4 22v-4a8 8 0 0 1 16 0v4',voice:'M12 3v18M8 7v10M4 10v4M16 6v12M20 9v6',music:'M9 18V5l11-2v13M9 6l11-2M3 18a3 2 0 1 0 6 0 3 2 0 1 0-6 0M14 16a3 2 0 1 0 6 0 3 2 0 1 0-6 0',record:'M12 3a9 9 0 1 0 0 18 9 9 0 1 0 0-18M12 8a4 4 0 1 0 0 8 4 4 0 1 0 0-8',folder:'M3 5h7l2 3h9v12H3z',caption:'M3 5h18v14H3zM10 10H7v4h3M17 10h-3v4h3',text:'M4 4h16M12 4v16M8 20h8',template:'M3 3h18v18H3zM3 9h18M10 9v12',shape:'M3 3h8v8H3zM17 12a5 5 0 1 0 0 10 5 5 0 1 0 0-10',undo:'M8 6L3 11l5 5M3 11h12a5 5 0 0 1 0 10',redo:'M16 6l5 5-5 5M21 11H9a5 5 0 0 0 0 10',trash:'M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7',copy:'M8 8h13v13H8zM16 8V3H3v13h5',close:'M5 5l14 14M19 5L5 19',download:'M12 3v12M6 10l6 6 6-6M3 17v4h18v-4',comment:'M3 3h18v14H9l-6 4zM7 8h10M7 12h7',share:'M8 12l9-6M8 12l9 6M5 9a3 3 0 1 0 0 6 3 3 0 1 0 0-6M19 2a3 3 0 1 0 0 6 3 3 0 1 0 0-6M19 16a3 3 0 1 0 0 6 3 3 0 1 0 0-6',search:'M10 3a7 7 0 1 0 0 14 7 7 0 1 0 0-14M15 15l6 6',spark:'M12 2l3 7 7 3-7 3-3 7-3-7-7-3 7-3z',check:'M4 12l5 5L20 6',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 1 0 0-18M12 6v6l4 3',menu:'M4 6h16M4 12h16M4 18h16',back:'M15 5l-7 7 7 7',star:'M12 2l3 6 7 1-5 5 1 8-6-4-6 4 1-8-5-5 7-1z',more:'M5 12h.01M12 12h.01M19 12h.01',arrow:'M12 20V4M5 11l7-7 7 7',settings:'M4 6h16M4 12h16M4 18h16M8 3v6M16 9v6M10 15v6',edit:'M3 17L16 4l4 4L7 21H3zM14 6l4 4'};
const icon=(name)=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.spark}"/></svg>`;
const btn=(action,name,ico,cls='round',extra='')=>`<button class="${cls}" data-action="${action}" title="${esc(name)}" aria-label="${esc(name)}" ${extra}>${ico?icon(ico):''}${cls.split(' ').includes('round')?'':esc(name)}</button>`;
const logo=()=>`<a class="logo" href="/vids"><span class="logo-mark">${icon('play')}</span><span>OpenVid</span></a>`;
const state={record:null,doc:null,panel:null,selected:null,index:0,undo:[],redo:[],assets:[],models:[],config:{},time:0,playing:false,dirty:false,saving:false,savePromise:null,jobs:[],library:[],filter:'all',zoom:1};
let toastTimer,saveTimer,pollTimer,chooserAspect='16:9',recording=null,pollBusy=false;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),5000)}
async function api(path,options={}){const resp=await fetch(path,{...options,headers:options.body instanceof FormData?{}:{'Content-Type':'application/json',...(options.headers||{})}});if(resp.status===401){auth();throw Error('Enter your OpenVid access token to continue')}const data=await resp.json().catch(()=>({}));if(!resp.ok)throw Error(typeof data.detail==='string'?data.detail:data.error||JSON.stringify(data.detail)||'Request failed');return data}
const post=(path,body={})=>api(path,{method:'POST',body:JSON.stringify(body)});
const connections=connectionsPanel({api,post,showDialog,toast,esc,refresh:async()=>{const [models,config]=await Promise.all([api('/api/models'),api('/api/vids/config')]);state.models=models.models;state.config=config;if(state.record)renderPanel()}});
const stockPanel=createStockPanel({state,$,esc,icon,api,post,insertAsset,toast});
const current=()=>state.doc.scenes[state.index];
const selected=()=>[...current().layers,...state.doc.audio].find(l=>l.id===state.selected);
const format=t=>`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;
function checkpoint(){state.undo.push(clone(state.doc));if(state.undo.length>80)state.undo.shift();state.redo=[]}
function changed(){stopPlayback();state.index=Math.max(0,Math.min(state.index,state.doc.scenes.length-1));const start=sceneStart(state.doc,state.index);if(state.time<start||state.time>=start+current().duration)state.time=start;state.dirty=true;clearTimeout(saveTimer);saveTimer=setTimeout(()=>save().catch(error),650);updateSave();renderCanvas();renderTimeline()}
function mutate(fn){checkpoint();fn();changed()}
function error(e){toast(e.message||String(e));console.error(e)}
function updateSave(){const node=$('#save-status');if(node)node.textContent=state.saving?'Saving…':state.dirty?'Unsaved changes':'All changes saved'}
async function save(){clearTimeout(saveTimer);if(state.savePromise){await state.savePromise;if(state.dirty)return save();return}if(!state.dirty||!state.record)return;const sent=clone(state.doc),did=state.record.id,revision=state.record.revision;state.saving=true;updateSave();state.savePromise=(async()=>{try{const result=await api(`/api/vids/${did}`,{method:'PUT',body:JSON.stringify({revision,document:sent})});if(state.record?.id!==did)return;state.record={...result};state.dirty=JSON.stringify(state.doc)!==JSON.stringify(sent)}catch(e){if(e.message.includes('Another editor')){showDialog('This video changed',`<p class="panel-note">Another tab saved a newer version. Your changes are still here. Save a copy to keep both versions, or reload the latest saved video.</p>${btn('conflict-copy','Save my changes as a copy','copy','pill primary')}${btn('reload','Reload saved video','clock','pill')}`);throw e}throw e}finally{state.saving=false;state.savePromise=null;updateSave()}})();await state.savePromise;if(state.dirty)await save()}
function showDialog(title,body,large=false){modal.className=large?'':'compact-dialog';modal.innerHTML=`<div class="dialog-header"><h2>${title}</h2>${btn('close-modal','Close','close')}</div><div class="dialog-body">${body}</div>`;if(!modal.open)modal.showModal()}
function auth(){clearInterval(pollTimer);app.innerHTML=`<div class="auth">${logo()}<h2>Welcome to OpenVid</h2><p class="panel-note">Enter your OpenVid access token to open your video workspace.</p><input id="invite" placeholder="Invite code" aria-label="Invite code" autocomplete="off">${btn('sign-in','Open Vids','arrow','pill primary')}<a href="/">Request an invite</a></div>`}
async function init(){const status=await api('/api/invite/status');if(!status.invited)return auth();const [models,config]=await Promise.all([api('/api/models'),api('/api/vids/config')]);(config.voice_studio?api('/api/voices/config'):Promise.resolve({languages:[]})).then(v=>{state.voiceLanguages=v.languages||[];const select=$('#voice-language');if(select){const value=select.value;select.innerHTML='<option value="">Auto detect</option>'+state.voiceLanguages.map(l=>`<option value="${esc(l.language_id)}">${esc(l.name)}</option>`).join('');select.value=value}}).catch(()=>{});state.models=models.models.filter(m=>m.ready);state.config=config;const id=location.pathname.split('/')[2];if(id)await openDoc(id);else await home();clearInterval(pollTimer);pollTimer=setInterval(poll,3000)}
async function home(){stopPlayback();state.record=null;state.doc=null;state.library=await api('/api/vids');history.replaceState(null,'','/vids');renderHome()}
function renderHome(){app.innerHTML=`<header class="home-header">${btn('home-filter','Library options','menu')}${logo()}<input class="search" id="library-search" placeholder="Search videos" aria-label="Search videos">${btn('connections','Connections','settings','pill')}<div class="avatar">O</div></header><main class="home-main"><div class="section-title">Start a new video</div><div class="starter-row"><button class="starter" data-action="new"><div class="starter-art" style="color:#7b7de0;font-weight:400">+</div><small>Blank video</small></button>${templates.slice(0,5).map((t,i)=>`<button class="starter" data-action="new-template" data-index="${i}"><div class="starter-art mini-template" style="background:${t.color};color:${t.ink||'#31443e'}">${t.title}</div><small>${t.name}</small></button>`).join('')}</div><div class="row spread"><div class="section-title">${state.filter==='trash'?'Trash':'Recent videos'}</div><div class="row"><select id="library-filter" aria-label="Filter videos"><option value="all" ${state.filter==='all'?'selected':''}>All videos</option><option value="starred" ${state.filter==='starred'?'selected':''}>Starred</option><option value="trash" ${state.filter==='trash'?'selected':''}>Trash</option></select>${btn('home','Refresh','clock')}</div></div><div class="doc-grid" id="doc-grid"></div></main>`;renderLibrary()}
function renderLibrary(){const query=($('#library-search')?.value||'').toLowerCase();const docs=state.library.filter(d=>d.name.toLowerCase().includes(query)&&(state.filter==='trash'?d.trashed:!d.trashed)&&(state.filter!=='starred'||d.starred));$('#doc-grid').innerHTML=docs.map(d=>`<article class="doc-card"><button data-action="open-doc" data-id="${d.id}" style="width:100%;padding:0;text-align:left"><div class="doc-cover" style="background:${esc(d.background||'#e9eef5')};color:${esc(d.color||'#202124')}">${d.cover?`<img src="${esc(d.cover)}" alt="" loading="lazy">`:`<span>${esc(d.title||d.name)}</span>`}</div><div class="doc-bottom">${icon('video')}<div><strong>${esc(d.name)}</strong><small>${d.scenes} scenes · ${new Date(d.updated*1000).toLocaleDateString()}</small></div></div></button>${btn('doc-menu','Video options','more','round more',`data-id="${d.id}"`)}</article>`).join('')||'<p class="empty">No videos here yet. Start with a blank video or a template.</p>'}
async function newDoc(doc=blank(),choose=true){await save();const created=await post('/api/vids',doc);await openDoc(created.id);if(choose)chooser()}
async function openDoc(id){state.record=await api('/api/vids/'+id);state.doc=clone(state.record.document);state.index=0;state.selected=null;state.multi=[];state.undo=[];state.redo=[];state.dirty=false;state.panel=null;state.jobs=JSON.parse(localStorage.getItem('vids-jobs-'+id)||'[]');const project=await api('/api/projects/'+state.record.project_id);state.assets=project.assets;history.replaceState(null,'','/vids/'+id);document.title=state.doc.name+' – OpenVid';renderEditor();for(const id of new Set([...(state.record.exports||[]).map(e=>e.job_id),...Object.values(state.record.requests||{})])){const j=await api('/api/jobs/'+id).catch(()=>null);if(j&&!j.context)j.context={auto:false};if(j&&!state.jobs.some(x=>x.id===j.id))state.jobs.push(j)}renderJobs()}
const rail=[['ai','AI Video','video'],['avatar','Avatar','person'],['voice','Voiceover','voice'],['music','Music','music'],['image','Image','image'],['record','Record','record'],['uploads','Uploads','folder'],['stock','Stock','image'],['captions','Captions','caption'],['text','Text','text'],['templates','Templates','template'],['shapes','Shapes','shape']];
function renderEditor(){app.innerHTML=`<header class="topbar"><a class="logo" href="/vids" aria-label="Vids home"><span class="logo-mark">${icon('play')}</span></a><div><div class="row"><input class="doc-title" id="doc-name" aria-label="Video title" value="${esc(state.doc.name)}">${btn('star',state.doc.starred?'Unstar video':'Star video','star','round')}<span class="save-status" id="save-status">All changes saved</span></div><nav class="menu-row">${['File','Edit','View','Insert','Format','Scene','Arrange','Tools','Help'].map(x=>`<button data-action="menu" data-menu="${x}">${x}</button>`).join('')}</nav></div><div class="grow"></div>${btn('comments','Comments','comment')}${btn('play','Play','play','pill')}${btn('connections','Connections','settings')}${btn('share','Share','share','pill primary')}<div class="avatar">O</div></header><div class="toolbar">${btn('chooser','Start creating','plus','tool-button')}<span class="divider"></span>${btn('undo','Undo','undo','tool-button')}${btn('redo','Redo','redo','tool-button')}<span class="divider"></span>${btn('zoom','Fit ▾','search','tool-button')}${btn('text-add','Text box','text','tool-button')}${btn('uploads','Upload','folder','tool-button')}${btn('shapes','Shape','shape','tool-button')}<span class="divider"></span>${btn('properties','Format options','settings','tool-button')}${btn('styles','Styles','template','tool-button optional')}${btn('scene-settings','Scene','settings','tool-button optional')}${btn('animate','Animate','spark','tool-button optional')}<div class="grow"></div>${btn('assistant','Ask OpenVid','spark','tool-button')}${btn('export','Download','download','tool-button')}</div><div class="editor-grid" id="editor-grid"><main class="working-area"><div class="canvas-wrap" id="canvas-wrap"><div class="canvas-shell" id="canvas-shell"><div class="canvas" id="canvas" role="region" aria-label="Video canvas"></div></div></div><div class="scene-footer"><button class="tool-button" data-action="timing">${icon('template')} Show timing</button><div class="time-controls">${btn('previous-scene','Previous scene','back')}${btn('play','Play or pause','play')}<span class="time-label" id="time-label"></span><input id="playhead" class="scrubber" type="range" min="0" max="${total(state.doc)}" step=".01" value="0" aria-label="Playhead">${btn('next-scene','Next scene','back','round',`style="transform:rotate(180deg)"`)}</div><button class="tool-button" data-action="zoom">100% ▾</button></div><section class="timeline" aria-label="Scene timeline"><div class="filmstrip" id="filmstrip"></div><div class="trackbar" id="trackbar"></div></section></main><aside class="side-panel" id="side-panel"></aside><nav class="rail" aria-label="Insertion">${rail.map(([p,n,i])=>btn(p,n,i,'',`data-panel="${p}"`)).join('')}</nav></div>`;renderCanvas();renderTimeline();renderPanel();new ResizeObserver(resizeCanvas).observe($('#canvas-wrap'));}
function resizeCanvas(){if(!state.doc||!$('#canvas'))return;const [w,h]=dimensions(state.doc.aspect);const wrap=$('#canvas-wrap');const scale=Math.max(.04,Math.min((wrap.clientWidth-64)/w,(wrap.clientHeight-64)/h))*state.zoom;const shell=$('#canvas-shell');shell.style.width=w*scale+'px';shell.style.height=h*scale+'px';const canvas=$('#canvas');canvas.style.width=w+'px';canvas.style.height=h+'px';canvas.style.transform=`scale(${scale})`;}
function renderCanvas(){if(!state.doc||!$('#canvas'))return;const s=current(),[w,h]=dimensions(state.doc.aspect),canvas=$('#canvas');canvas.style.background=s.background;const localTime=Math.min(s.duration-.001,Math.max(0,state.time-sceneStart(state.doc,state.index)));canvas.innerHTML=s.layers.filter(l=>(l.id===state.selected||(localTime>=l.start&&localTime<l.start+l.duration))&&!l.hidden&&l.kind!=='audio'&&(!l.caption||state.doc.captions)).map(l=>`<div data-layer="${l.id}" class="canvas-layer ${l.id===state.selected||(state.multi||[]).includes(l.id)?'selected':''} ${l.locked?'locked':''}" style="${layerStyle(l,w,h)}" role="button" aria-label="${esc(l.kind==='text'?l.text.slice(0,50):l.kind+' layer')}" tabindex="0">${l.kind==='text'?esc(l.text):l.kind==='image'?`<img src="${esc(l.url)}" alt="">`:l.kind==='video'?`<video src="${esc(l.url)}#t=${(l.trim||0)+Math.max(0,localTime-l.start)*(l.speed||1)}" muted preload="metadata"></video>`:''}${state.selected===l.id&&!l.locked?'<span class="resize-handle" data-resize="true"></span>':''}</div>`).join('');if(!s.layers.length)canvas.innerHTML='<div class="empty-canvas">Create something worth watching.</div>';resizeCanvas();$('#time-label').textContent=`${format(state.time)} / ${format(total(state.doc))}`;$('#playhead').max=total(state.doc);$('#playhead').value=state.time;}
function renderTimeline(){if(!state.doc||!$('#filmstrip'))return;$('#filmstrip').innerHTML=state.doc.scenes.map((s,i)=>{const image=s.layers.find(l=>!l.hidden&&(l.kind==='image'||l.kind==='video'));const poster=image?.kind==='video'?state.assets.find(a=>a.url===image.url)?.poster:null;const title=s.layers.find(l=>l.kind==='text');return `<button class="scene-card ${i===state.index?'active':''}" data-action="select-scene" data-index="${i}" draggable="true" data-scene-index="${i}" aria-label="Scene ${i+1}: ${esc(s.name)}"><div class="scene-thumb" style="background:${s.background};${image?.kind==='image'||poster?`background-image:url('${esc(poster||image.url)}');background-size:cover;`:''}">${image?.kind==='video'&&!poster?`<video class="scene-video-thumb" src="${esc(image.url)}#t=${image.trim||.1}" muted preload="metadata"></video>`:''}${!image&&title?`<span style="position:absolute;top:25%;left:8%;right:8%;font:14px ${title.font};color:${title.color}">${esc(title.text.slice(0,70))}</span>`:''}<span class="scene-label"><span>${i+1} · ${esc(s.name.slice(0,14))}</span><span>${Number(s.duration.toFixed(1))}s</span></span></div></button>`}).join('')+btn('add-scene','Add scene','plus','scene-plus');$('#trackbar').innerHTML=[...current().layers.filter(l=>l.kind==='audio'),...state.doc.audio].map(l=>`<button class="track-chip" data-action="select-layer" data-id="${l.id}">${icon('music')} ${esc(l.text||'Audio')} · ${l.duration.toFixed(1)}s</button>`).join('');extras.timeline();}
function chooser(){chooserAspect=state.doc.aspect;showDialog('<span>Hello.</span> Let’s start creating.',`<div class="aspect-switch">${[['16:9','Landscape'],['9:16','Portrait'],['1:1','Square']].map(([a,n])=>`<button data-action="choose-aspect" data-aspect="${a}" class="${a===chooserAspect?'active':''}">${a===chooserAspect?'✓ ':''}${n}</button>`).join('')}</div><div class="creation-grid">${[['ai','Create AI videos','Turn text and images into short videos','video'],['edit-video','Edit videos','Transform your videos with AI','edit'],['personal-avatar','Personal avatar','Use your own portrait to star in a video','person'],['avatar','AI avatar','Write a script and bring a presenter to life','person'],['docs','Docs to video','Turn documents or PDFs into video scenes','text'],['slides','Slides to video','Turn presentations into narrated videos','template'],['record','Record','Record yourself, your screen, or both','record'],['uploads','Upload','Use media from your computer','folder'],['templates','Templates','Start with a beautifully designed template','template'],['blank','Blank vid','Start with a blank canvas','plus']].map(([a,n,d,i],idx)=>`<button class="creation-card" data-action="choose-feature" data-feature="${a}"><div class="creation-art art-${idx}">${icon(i)}</div><div class="creation-info"><strong>${n}${idx<5?'<span class="badge">New</span>':''}</strong><p>${d}</p></div></button>`).join('')}</div>`,true)}
function openPanel(name){if(recording)return toast('Stop and save the recording before changing panels');state.panel=state.panel===name?null:name;renderPanel();resizeCanvas()}
const field=(label,key,value,type='number',extra='')=>`<label>${label}<input type="${type}" data-field="${key}" value="${esc(value)}" ${extra}></label>`;
const select=(label,key,value,options)=>`<label>${label}<select data-field="${key}">${options.map(o=>{const [v,n]=Array.isArray(o)?o:[o,o];return `<option value="${esc(v)}" ${value===v?'selected':''}>${esc(n)}</option>`}).join('')}</select></label>`;
const assetOptions=(kind,empty='Choose an asset')=>`<option value="">${empty}</option>${state.assets.filter(a=>!kind||a.kind===kind).map(a=>`<option value="${a.id}">${esc((a.prompt||a.model_label||a.kind).slice(0,70))}</option>`).join('')}`;
function renderPanel(){if(!$('#side-panel'))return;$('#editor-grid').classList.toggle('panel-open',!!state.panel);document.querySelectorAll('.rail button').forEach(b=>b.classList.toggle('active',b.dataset.panel===state.panel));const p=state.panel;if(!p)return;const names={ai:'AI video',image:'Create an image',voice:'Voiceover',music:'Music',avatar:'AI avatar','personal-avatar':'Personal avatar',uploads:'Uploads',stock:'Stock media',captions:'Captions',text:'Text',shapes:'Shapes',templates:'Templates',properties:'Format options',layers:'Layers & timing',comments:'Comments',history:'Version history',assistant:'Ask OpenVid',record:'Recording studio','edit-video':'Edit video','scene-settings':'Scene settings',docs:'Docs to video',slides:'Slides to video',jobs:'Activity'};let body='';const l=selected(),s=current();
  if(['ai','image'].includes(p)){const kind=p==='ai'?'video':'image';const models=state.models.filter(m=>m.kind===kind&&m.id!=='seedance-2.5-wiro');body=`<p class="panel-note">Describe the scene you want. Generated media is saved to this video’s library.</p><textarea id="gen-prompt" placeholder="A cinematic close-up of a dew-covered leaf in soft morning light…" aria-label="Generation prompt"></textarea><label>Model<select id="gen-model">${models.map(m=>`<option value="${esc(m.id)}" ${p==='image'&&m.id==='nano-banana-2'?'selected':''}>${esc(m.provider||m.label)} · ${m.tier}</option>`).join('')}</select></label>${p==='ai'?'<label>Duration<input id="gen-duration" type="number" value="6" min="3" max="30"></label>':''}<label>Reference image (optional)<select id="gen-reference">${assetOptions('image','No reference')}</select></label><p class="panel-note" id="estimate">Billed to your selected provider. Model prices vary; check your provider dashboard.</p>${btn('generate','Generate','spark','full-button solid',!state.config.capabilities?.[kind]?'disabled':'')}<div id="panel-jobs"></div>`}
  if(p==='voice')body=`<p class="panel-note">Use your selected speech provider. Reuse the same voice across scenes. Manage providers in Connections.</p><textarea id="voice-text" placeholder="Write your narration…" aria-label="Narration text">${esc(s.notes)}</textarea><label>Voice<select id="voice-name">${(state.config.voices||[]).map(v=>`<option>${esc(v)}</option>`).join('')}</select></label><label>Language<select id="voice-language"><option value="">Auto detect</option>${(state.voiceLanguages?.length?state.voiceLanguages.map(l=>[l.language_id,l.name]):[['en','English'],['hi','Hindi'],['ml','Malayalam'],['ta','Tamil'],['te','Telugu'],['kn','Kannada'],['bn','Bengali'],['es','Spanish'],['fr','French'],['de','German'],['ar','Arabic'],['zh','Chinese'],['ja','Japanese'],['ko','Korean'],['pt','Portuguese'],['ru','Russian'],['it','Italian'],['id','Indonesian'],['tr','Turkish']]).map(([v,n])=>`<option value="${v}">${n}</option>`).join('')}</select></label>${btn('generate-voice','Create voiceover','voice','full-button solid')}<div class="row">${btn('record','Record voice','record','pill')}${btn('voice-library','Voice library',null,'pill')}</div><p class="panel-note">After inserting audio, use Format options to set a pause before speech, playback speed, volume, and fades.</p><div id="panel-jobs"></div>`;
  if(p==='music')body=`<p class="panel-note">Create a shared soundtrack with your selected music provider. Provider charges apply.</p><textarea id="music-prompt" aria-label="Music description" placeholder="Warm, gentle piano with a hopeful build. Instrumental, no vocals."></textarea><label>Length in seconds<input id="music-duration" type="number" min="3" max="600" value="${Math.ceil(Math.max(10,total(state.doc)))}"></label>${btn('generate-music','Generate music','music','full-button solid')}<p class="panel-note">Music spans scenes and includes a 3-second fade out by default.</p>${btn('upload-audio','Upload music','folder','full-button pill')}<div id="panel-jobs"></div>`;
  if(['avatar','personal-avatar'].includes(p))body=`<p class="panel-note">Choose an uploaded or AI-generated portrait and an audio clip. The fal avatar model selected in Connections generates the speaking video.</p><label>Portrait<select id="avatar-face">${assetOptions('image')}</select></label>${btn('upload-avatar','Upload portrait','folder','full-button pill')}<label>Speech audio<select id="avatar-audio">${assetOptions('audio','Create a voiceover first')}</select></label><label>Direction<textarea id="avatar-prompt" placeholder="A friendly presenter speaking naturally to camera."></textarea></label><label class="inline"><input type="checkbox" id="avatar-consent"> I have permission to use this likeness and voice.</label>${btn('generate-avatar','Generate avatar','person','full-button solid')}<div id="panel-jobs"></div>`;
  if(p==='edit-video')body=`<p class="panel-note">Edit an existing clip with the video-edit model selected in Connections.</p><label>Video<select id="edit-asset">${assetOptions('video')}</select></label><textarea id="edit-prompt" aria-label="Video edit instruction" placeholder="Make the sky a warm sunset. Preserve the person and camera motion."></textarea>${btn('generate-edit','Create edit','edit','full-button solid')}<div id="panel-jobs"></div>`;
  if(p==='text')body=`<p class="panel-note">Add a text box, then double-click it on the canvas to edit.</p><button class="text-preset" data-action="text-add" data-size="96" style="font-size:26px">Add a title</button><button class="text-preset" data-action="text-add" data-size="60" style="font-size:20px">Add a subtitle</button><button class="text-preset" data-action="text-add" data-size="36">Add body text</button>`;
  if(p==='shapes')body=`<p class="panel-note">Insert a shape. Drag to position and resize it on the canvas.</p><div class="shape-grid">${[['rectangle','▭'],['ellipse','○'],['triangle','△'],['line','—']].map(([x,n])=>`<button data-action="shape-add" data-shape="${x}" aria-label="${x}">${n}</button>`).join('')}</div>`;
  if(p==='templates')body=`<p class="panel-note">Add a fully editable scene.</p>${templates.map((t,i)=>`<button class="template-card" data-action="insert-template" data-index="${i}" style="background:${t.color};color:${t.ink||'#31443e'}">${t.title}<small>${t.name}</small></button>`).join('')}`;
  if(p==='uploads')body=`${btn('upload','Upload media','folder','full-button pill')}<input id="asset-search" placeholder="Search this video’s media" aria-label="Search uploads"><div class="asset-grid" id="asset-grid">${assetCards(state.assets)}</div>`;
  if(p==='stock')body=stockPanel.html();
  if(p==='captions')body=`<p class="panel-note">Transcribe speech with your selected caption provider, or import an SRT file. Captions become editable timed text layers.</p><label>Speech or video<select id="caption-asset">${assetOptions(null)}</select></label>${btn('generate-captions','Generate captions','caption','full-button solid')}${btn('import-srt','Import SRT','folder','full-button pill')}${btn('download-srt','Download subtitles','download','full-button pill')}<label class="inline"><input id="captions-visible" type="checkbox" ${state.doc.captions?'checked':''}> Show captions in preview and export</label><div id="panel-jobs"></div>`;
  if(p==='properties'){if(!l)body='<p class="panel-note">Select a text, shape, image, video, or audio layer to edit its properties.</p>';else body=`${l.kind==='text'?`<label>Text<textarea data-field="text">${esc(l.text)}</textarea></label>${select('Font','font',l.font,['Arial','Georgia','Verdana','Courier New','Trebuchet MS'])}<div class="fields">${field('Font size','fontSize',l.fontSize)}${field('Text color','color',l.color,'color')}</div>${select('Alignment','align',l.align,['left','center','right'])}<div class="row"><label class="inline"><input type="checkbox" data-field="bold" ${l.bold?'checked':''}> Bold</label><label class="inline"><input type="checkbox" data-field="italic" ${l.italic?'checked':''}> Italic</label></div>`:''}${l.kind==='shape'?field('Fill','fill',l.fill,'color'):''}${l.kind!=='audio'?`<div class="fields">${field('Left (%)','x',l.x)}${field('Top (%)','y',l.y)}${field('Width (%)','w',l.w)}${field('Height (%)','h',l.h)}${field('Rotation','rotation',l.rotation)}${field('Opacity','opacity',l.opacity,'number','min="0" max="1" step=".05"')}</div>${select('Animation','animation',l.animation,['none','fade','rise','zoom','slide'])}`:''}<div class="fields">${field('Start / pause (s)','start',l.start,'number','min="0" step=".1"')}${field('Visible duration (s)','duration',l.duration,'number','min=".1" step=".1"')}</div>${['audio','video'].includes(l.kind)?`<div class="fields">${field('Source trim (s)','trim',l.trim,'number','min="0" step=".1"')}${field('Speed','speed',l.speed,'number','min=".25" max="4" step=".05"')}${field('Volume','volume',l.volume,'number','min="0" max="1" step=".05"')}${field('Fade in (s)','fadeIn',l.fadeIn,'number','min="0" step=".1"')}${field('Fade out (s)','fadeOut',l.fadeOut,'number','min="0" step=".1"')}</div>`:''}${['image','video'].includes(l.kind)?select('Image fit','fit',l.fit,['cover','contain'])+`<div class="fields">${field('Crop X (%)','cropX',l.cropX??50)}${field('Crop Y (%)','cropY',l.cropY??50)}${field('Brightness','brightness',l.brightness??1,'number','min="0" max="3" step=".1"')}${field('Contrast','contrast',l.contrast??1,'number','min="0" max="3" step=".1"')}${field('Saturation','saturation',l.saturation??1,'number','min="0" max="3" step=".1"')}</div>`:''}${l.kind!=='audio'?`<div class="fields">${field('Rounded corners (%)','radius',l.radius||0)}${field('Border width','borderWidth',l.borderWidth||0)}${field('Border color','borderColor',l.borderColor||'#202124','color')}</div><label class="inline"><input type="checkbox" data-field="shadow" ${l.shadow?'checked':''}>Drop shadow</label>`:''}<div class="row">${btn('duplicate-layer','Duplicate','copy','pill')}${btn('delete-layer','Delete','trash','pill danger')}</div>`;}
  if(p==='scene-settings')body=`${field('Scene name','scene.name',s.name,'text')}${field('Duration (seconds)','scene.duration',s.duration,'number','min=".25" max="300" step=".25"')}${field('Background','scene.background',s.background,'color')}${select('Transition','scene.transition',s.transition,['none','fade','slide'])}${select('Video shape','doc.aspect',state.doc.aspect,[['16:9','Landscape 16:9'],['9:16','Portrait 9:16'],['1:1','Square 1:1']])}<label>Script / speaker notes<textarea data-field="scene.notes">${esc(s.notes)}</textarea></label>${btn('voice','Create narration from script','voice','full-button pill')}<div class="row">${btn('duplicate-scene','Duplicate','copy','pill')}${btn('delete-scene','Delete','trash','pill danger')}</div>`;
  if(p==='layers')body=`<p class="panel-note">Layers paint from bottom to top. Select one to edit timing and appearance.</p><div class="layer-list">${[...s.layers].reverse().map(l=>`<div class="layer-row ${l.id===state.selected?'active':''}"><button data-action="select-layer" data-id="${l.id}">${icon(l.kind==='audio'?'music':l.kind==='shape'?'shape':l.kind==='text'?'text':'image')}</button><span>${esc(l.text||l.kind)}</span><button data-action="toggle-lock" data-id="${l.id}" aria-label="Lock layer">${l.locked?'🔒':'◇'}</button><button data-action="toggle-hidden" data-id="${l.id}" aria-label="Hide layer">${l.hidden?'○':'●'}</button></div>`).join('')}</div><div class="row">${btn('layer-up','Bring forward','arrow','pill')}${btn('layer-down','Send backward','arrow','pill')}</div>${btn('properties','Edit selected layer','settings','full-button pill')}`;
  if(p==='comments')body=`<input id="comment-author" placeholder="Your name" aria-label="Comment author" value="${esc(localStorage.getItem('vids-author')||'')}"><textarea id="comment-text" placeholder="Leave a comment on this scene…" aria-label="Comment"></textarea>${btn('add-comment','Comment','comment','full-button primary')}<div id="comment-list">${commentsHTML()}</div>`;
  if(p==='history')body='<p class="panel-note">Restore an earlier saved version. Your current version is kept in history.</p><div id="history-list">Loading versions…</div>';
  if(p==='assistant')body=`<p class="panel-note">Describe a new video or an edit. Review the proposed scenes before applying them. Generate the complete video from your scripts, or create individual media from the side panels.</p><textarea id="assistant-prompt" placeholder="Create a 30-second onboarding video with five scenes…" aria-label="Assistant prompt"></textarea>${btn('assistant-plan','Draft changes','spark','full-button solid')}${btn('produce-form','Generate full video','video','full-button pill')}<div id="assistant-result"></div>`;
  if(p==='record')body=`<p class="panel-note">Record your camera, screen, or voice. Recording starts after you grant browser permission.</p><label>Record<select id="record-mode"><option value="camera">Camera and microphone</option><option value="screen">Screen and microphone</option><option value="both">Screen, camera, and microphone</option><option value="voice">Microphone only</option></select></label><label>Teleprompter<textarea id="teleprompter">${esc(s.notes)}</textarea></label><label>Teleprompter speed<input id="prompter-speed" type="range" min="0" max="90" value="30"></label><div id="prompter-stage" class="teleprompter-stage" hidden></div><video id="record-preview" class="record-preview" autoplay muted playsinline hidden></video>${btn('record-start','Start recording','record','full-button solid')}${btn('record-stop','Stop and save','check','full-button pill','disabled')}<span id="record-status" class="panel-note"></span>`;
  if(['docs','slides'].includes(p))body=`<p class="panel-note">${p==='slides'?'Import a PowerPoint (.pptx) file. Slide layouts are preserved as images with extracted script notes.':'Import PDF, Word, Markdown, or text. PDF pages preserve their layout; text becomes editable scenes.'}</p>${btn('import-document','Choose document','folder','full-button primary')}<p class="panel-note">For Google Docs or Slides, download a DOCX, PDF, or PPTX first. Import replaces the current scenes; the earlier version remains in history.</p>${btn('assistant','Summarize into new scenes','spark','full-button pill')}`;
  if(p==='jobs')body='<div id="panel-jobs"></div>';
  if(extras.panels[p])body=extras.panels[p]();
  $('#side-panel').innerHTML=`<div class="panel-head"><h2>${names[p]||({styles:'Customize styles',storyboard:'Storyboard',transcript:'Transcript'}[p])||p}</h2>${btn('close-panel','Close panel','close')}</div><div class="panel-body">${body}</div>`;renderJobs();if(p==='history')loadHistory().catch(error);
}
function assetCards(assets){return assets.filter(a=>a.source!=='transcript').map(a=>`<button class="asset" data-action="insert-asset" data-id="${a.id}" title="Insert ${esc(a.prompt||a.kind)}">${a.kind==='image'?`<img loading="lazy" src="${esc(a.url)}" alt="${esc(a.prompt?.slice(0,60)||'Image')}">`:a.kind==='video'?a.poster?`<img loading="lazy" src="${esc(a.poster)}" alt="Video">`:`<video src="${esc(a.url)}" muted preload="metadata"></video>`:`<div class="audio-art">${icon('music')}</div>`}<small>${esc((a.prompt||a.model_label||a.kind).slice(0,70))}</small></button>`).join('')||'<p class="panel-note">Uploaded and generated media appears here.</p>'}
function commentsHTML(){return (state.record.comments||[]).slice().reverse().map(c=>`<div class="comment"><strong>${esc(c.author)}</strong><small> · ${new Date(c.at*1000).toLocaleString()}</small><p>${esc(c.text)}</p><button data-action="resolve-comment" data-id="${c.id}" class="tool-button">${c.resolved?'Reopen':'Resolve'}</button>${c.resolved?' ✓ Resolved':''}</div>`).join('')}
async function loadHistory(){const list=await api(`/api/vids/${state.record.id}/history`);if($('#history-list'))$('#history-list').innerHTML=list.map(h=>`<button class="full-button" data-action="restore-version" data-version="${h.revision}">Version ${h.revision} · ${new Date(h.at*1000).toLocaleString()}</button>`).join('')||'<p class="panel-note">Your first saved change will appear here.</p>'}
function insertAsset(a,context={}){stopPlayback();mutate(()=>{const s=state.doc.scenes.find(s=>s.id===context.scene_id)||current();const dur=a.duration||s.duration;const l=layer(a.kind,{url:a.url,text:a.kind==='audio'?(a.prompt||'Audio').slice(0,100):'',x:0,y:0,w:100,h:100,duration:Math.min(dur,s.duration),volume:a.kind==='video'?1:1});if(context.music){l.duration=total(state.doc);l.volume=.2;l.fadeOut=Math.min(3,l.duration);state.doc.audio.push(l)}else{if(a.kind==='video'&&s.layers.length===0){s.duration=dur;l.duration=dur}if(a.kind==='audio'){l.duration=dur;s.duration=Math.max(s.duration,dur)}s.layers.push(l)}state.index=state.doc.scenes.indexOf(s);state.selected=l.id});toast('Added to your video');}
async function queue(path,body,context={}){await save();const res=await post(path,body);for(const id of res.jobs){if(!state.jobs.some(j=>j.id===id))state.jobs.push({id,status:'queued',prompt:body.prompt||body.kind||'Generating',context:{scene_id:current().id,...context},document_id:state.record.id})}localStorage.setItem('vids-jobs-'+state.record.id,JSON.stringify(state.jobs));renderJobs();toast('Generation started. You can keep editing.');return res}
function renderJobs(){const target=$('#panel-jobs');if(!target)return;const content=state.jobs.slice().reverse().map(j=>`<div class="job-row ${j.status==='error'?'error':''}"><strong>${j.status==='done'?'✓ Complete':j.status==='error'?'Could not finish':j.status==='running'?'Generating…':'Queued'}</strong><div>${esc(j.progress?.label||j.prompt?.slice(0,90)||'')}</div>${j.status==='error'?`<div>${esc(j.error)}</div>`:''}${j.vids_proposal&&!j.context?.applied?btn('apply-production','Apply generated scenes','check','full-button primary',`data-id="${j.id}"`):''}${j.status==='done'&&j.assets?.[0]?`<button class="tool-button" data-action="job-insert" data-id="${j.id}">${j.assets.some(a=>['vids-export','vids-production'].includes(a.source))?'View / download':'Insert result'}</button>`:''}</div>`).join('');if(target._rendered!==content){target.innerHTML=content;target._rendered=content}}
async function poll(){if(!state.record||pollBusy)return;pollBusy=true;try{await pollJobs()}catch(e){console.warn(e.message)}finally{pollBusy=false}}
async function pollJobs(){if(!state.record)return;const did=state.record.id;for(const j of [...state.jobs]){if(!['queued','running'].includes(j.status))continue;try{const fresh=await api('/api/jobs/'+j.id);if(state.record?.id!==did)return;Object.assign(j,fresh);if(j.status==='done'){state.assets=(await api('/api/projects/'+state.record.project_id)).assets;if(j.context?.captions){insertTranscript(j.assets[0].transcript,j.context.scene_id,j.context.asset_id)}else if(j.assets?.[0]&&j.context?.auto!==false&&j.assets[0].source!=='vids-export')insertAsset(j.assets[0],j.context||{});toast(j.assets?.[0]?.source==='vids-export'?'Your video is ready to download':'Generation complete')}if(j.status==='error'){state.assets=(await api('/api/projects/'+state.record.project_id)).assets;toast(j.error||'Generation failed')}}catch(e){console.warn(e.message)}}if(state.record?.id===did){localStorage.setItem('vids-jobs-'+did,JSON.stringify(state.jobs));renderJobs();if(!state.dirty&&!state.saving){const fresh=await api('/api/vids/'+did).catch(()=>null);if(fresh&&state.record?.id===did&&!state.dirty&&!state.saving&&fresh.revision>state.record.revision){state.record=fresh;state.doc=clone(fresh.document);state.index=Math.min(state.index,state.doc.scenes.length-1);renderCanvas();renderTimeline();toast('Loaded changes from another editor')}if(fresh&&state.record?.id===did)state.record.comments=fresh.comments}}}
function insertTranscript(data,sid,assetId){const words=data.words||data.timestamps||[];const cues=[];let batch=[];for(const w of words){if(w.type&&w.type!=='word')continue;batch.push(w);if(batch.length===7||/[.!?]$/.test(w.text||w.word||'')){cues.push({start:batch[0].start??batch[0].start_time,end:w.end??w.end_time,text:batch.map(x=>x.text||x.word||'').join(' ')});batch=[]}}if(batch.length)cues.push({start:batch[0].start??batch[0].start_time,end:batch.at(-1).end??batch.at(-1).end_time,text:batch.map(x=>x.text||x.word||'').join(' ')});if(!cues.length){toast('No timed speech found in this clip');return}mutate(()=>{const s=state.doc.scenes.find(s=>s.id===sid)||current();const asset=state.assets.find(a=>a.id===assetId),clip=s.layers.find(l=>l.url===asset?.url&&['audio','video'].includes(l.kind));const adjusted=clip?cues.map(c=>({...c,start:clip.start+(c.start-clip.trim)/clip.speed,end:clip.start+(c.end-clip.trim)/clip.speed})).filter(c=>c.end>clip.start&&c.start<clip.start+clip.duration).map(c=>({...c,start:Math.max(clip.start,c.start),end:Math.min(clip.start+clip.duration,c.end)})):cues;s.layers=s.layers.filter(l=>!l.caption).concat(captionLayers(adjusted,s.duration))});}
function stopPlayback(){state.playing=false;const p=$('hyperframes-player');if(p){p.pause();p.remove()}}
async function play(){if(state.playing){stopPlayback();return}const startTime=state.time;const shell=$('#canvas-shell');const player=document.createElement('hyperframes-player');player.className='preview-player';player.setAttribute('runtime-src',location.origin+'/vids-vendor/hyperframe.runtime.iife.js');player.setAttribute('srcdoc',compile(state.doc,{origin:location.origin}));const [w,h]=dimensions(state.doc.aspect);player.setAttribute('width',w);player.setAttribute('height',h);player.setAttribute('controls','');shell.append(player);state.playing=true;player.addEventListener('ready',()=>{player.seek(startTime>=total(state.doc)-.05?0:startTime);player.play()});player.addEventListener('timeupdate',e=>{state.time=e.detail.currentTime;$('#time-label').textContent=`${format(state.time)} / ${format(total(state.doc))}`;$('#playhead').value=state.time});player.addEventListener('ended',()=>{state.time=0;state.index=0;state.selected=null;stopPlayback();renderCanvas();renderTimeline()});player.addEventListener('error',e=>{toast(e.detail.message);stopPlayback()});}
function chooseFile(accept,handler,multiple=false){const input=$('#file-input');input.value='';input.accept=accept;input.multiple=multiple;input.onchange=async()=>{try{for(const file of input.files)await handler(file)}catch(e){error(e)}};input.click()}
async function uploadFile(file,insert=true){const data=new FormData();data.append('file',file);toast('Uploading '+file.name+'…');const a=await api(`/api/projects/${state.record.project_id}/upload`,{method:'POST',body:data});state.assets.unshift(a);if(insert)insertAsset(a);if(state.panel==='uploads')renderPanel();return a}
function download(name,content,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function showExport(){showDialog('Download video',`<p class="panel-note">Render your saved scenes with HyperFrames, including media, animations, captions, and mixed audio.</p><label>Format<select id="export-format"><option value="mp4">MP4 video</option><option value="webm">WebM video</option><option value="gif">Animated GIF (no audio)</option></select></label><div class="fields"><label>Resolution<select id="export-resolution"><option value="1080p">1080p</option><option value="720p">720p</option></select></label><label>Frame rate<select id="export-fps"><option>30</option><option>24</option><option>60</option></select></label></div>${btn('render-export','Render video','download','full-button solid')}<div id="export-history">${state.jobs.filter(j=>j.status==='done'&&j.assets?.[0]?.source==='vids-export').map(j=>`<a class="full-button pill" href="${esc(j.assets[0].url)}" download>${icon('download')} Download revision ${j.assets[0].vids_revision}</a>`).join('')}</div>`)}
function showMenu(name,anchor){$('.menu-pop')?.remove();const menus={File:[['New video','new'],['Make a copy','duplicate-doc'],['Rename','rename'],['Import document or slides','docs'],['Download video','export'],['Download project JSON','download-json'],['Download media credits','download-credits'],['Version history','history'],['Move to trash','trash-doc']],Edit:[['Undo','undo','⌘Z'],['Redo','redo','⌘⇧Z'],['Cut','cut-layer','⌘X'],['Copy','copy-layer','⌘C'],['Paste','paste-layer','⌘V'],['Select all','select-all','⌘A'],['Find and replace','find'],['Duplicate selected','duplicate-layer','⌘D'],['Delete selected','delete-layer','⌫']],View:[['Play video','play','Space'],['Canvas and timeline zoom','zoom'],['Fit canvas','fit'],['Full screen','full-screen'],['Show transcript','transcript'],['Show timing','timing'],['Layers and timing','layers'],['Comments','comments']],Insert:[['New scene','add-scene'],['Text box','text-add'],['Image','image'],['Video','ai'],['Audio','voice'],['Shape','shapes'],['Upload','uploads'],['Captions','captions']],Format:[['Customize styles','styles'],['Copy style','paint-copy'],['Apply copied style','paint-apply'],['Format options','properties'],['Animate','animate'],['Background','scene-settings']],Scene:[['New scene','add-scene'],['Split scene at playhead','split-scene','⌘⇧S'],['Split layer at playhead','split-layer'],['Duplicate scene','duplicate-scene'],['Delete scene','delete-scene'],['Move scene left','scene-left'],['Move scene right','scene-right'],['Duration and transition','scene-settings']],Arrange:[['Group','group'],['Ungroup','ungroup'],['Bring to front','front'],['Send to back','back'],['Align left','align-left'],['Align right','align-right'],['Align top','align-top'],['Align bottom','align-bottom'],['Distribute horizontally','distribute-x'],['Distribute vertically','distribute-y'],['Flip horizontally','flip-x'],['Flip vertically','flip-y'],['Rotate 90°','rotate-right'],['Bring forward','layer-up'],['Send backward','layer-down'],['Center horizontally','center-x'],['Center vertically','center-y']],Tools:[['Storyboard and scripts','storyboard'],['Preferences','preferences'],['Ask OpenVid','assistant'],['Edit video with AI','edit-video'],['Record','record'],['Document to video','docs'],['Slides to video','slides'],['Activity','jobs']],Help:[['Keyboard shortcuts','shortcuts'],['About OpenVid','about']]};const pop=document.createElement('div');pop.className='menu-pop';pop.innerHTML=(menus[name]||[]).map(([n,a,k])=>`<button data-action="${a}">${n}<kbd>${k||''}</kbd></button>`).join('');const r=anchor.getBoundingClientRect();pop.style.left=Math.min(r.left,innerWidth-260)+'px';pop.style.top=r.bottom+3+'px';document.body.append(pop)}
async function startRecording(){
  const stage=$('#prompter-stage');stage.textContent=$('#teleprompter').value;
  recording=await recordMedia({mode:$('#record-mode').value,preview:$('#record-preview'),onSaved:async file=>{await uploadFile(file);toast('Recording saved');renderPanel()},onState:active=>{if(!active)recording=null;const label=$('#record-status');if(label)label.textContent=active?'Recording… click Stop and save when finished.':'Recording stopped';const start=$('[data-action="record-start"]'),stop=$('[data-action="record-stop"]');if(start)start.disabled=active;if(stop)stop.disabled=!active},onError:error});
}
let proposedDoc=null;
async function action(a,b){const pid=state.record?.project_id;
  if(a==='connections')return connections.open();
  if(await connections.action(a,b))return;
  if(extras.actions[a])return extras.actions[a](b);
  if(rail.some(x=>x[0]===a)||['properties','layers','comments','history','assistant','edit-video','scene-settings','docs','slides','jobs','personal-avatar'].includes(a)){openPanel(a);return}
  if(a==='close-modal')return modal.close();if(a==='close-panel'){state.panel=null;renderPanel();resizeCanvas();return}
  if(a==='sign-in'){await post('/api/invite/redeem',{code:$('#invite').value});return init()}
  if(a==='home'){await save();return home()}if(a==='home-filter'){state.filter=state.filter==='trash'?'all':'trash';return renderHome()}
  if(a==='open-doc')return openDoc(b.dataset.id);if(a==='new')return newDoc();if(a==='new-template'){const d=blank();d.scenes=[applyTemplate(templates[+b.dataset.index])];d.name=templates[+b.dataset.index].name;return newDoc(d,false)}
  if(a==='doc-menu'){showDialog('Video options',`${btn('open-doc','Open video','video','full-button',`data-id="${b.dataset.id}"`)}${btn('library-duplicate','Make a copy','copy','full-button',`data-id="${b.dataset.id}"`)}${btn('library-trash',state.filter==='trash'?'Restore video':'Move to trash','trash','full-button',`data-id="${b.dataset.id}"`)}`);return}
  if(a==='library-duplicate'){const d=await post(`/api/vids/${b.dataset.id}/duplicate`);modal.close();return openDoc(d.id)}if(a==='library-trash'){await post(`/api/vids/${b.dataset.id}/trash`);modal.close();return home()}
  if(a==='chooser')return chooser();if(a==='choose-aspect'){mutate(()=>state.doc.aspect=b.dataset.aspect);return chooser()}
  if(a==='choose-feature'){modal.close();if(b.dataset.feature!=='blank')openPanel(b.dataset.feature);return}
  if(a==='star'){mutate(()=>state.doc.starred=!state.doc.starred);return}if(a==='rename')return $('#doc-name').focus();if(a==='menu')return showMenu(b.dataset.menu,b);
  if(a==='undo'||a==='redo'){const from=state[a],to=state[a==='undo'?'redo':'undo'];if(from.length){to.push(clone(state.doc));state.doc=from.pop();state.index=Math.min(state.index,state.doc.scenes.length-1);state.selected=null;changed();renderPanel()}return}
  if(a==='add-scene'){mutate(()=>{state.doc.scenes.splice(state.index+1,0,scene({name:'Scene '+(state.doc.scenes.length+1)}));state.index++;state.selected=null});return}
  if(a==='select-scene'){state.multi=[];stopPlayback();state.index=+b.dataset.index;state.selected=null;state.time=sceneStart(state.doc,state.index);renderCanvas();renderTimeline();renderPanel();return}
  if(a==='previous-scene'||a==='next-scene'){state.index=Math.max(0,Math.min(state.doc.scenes.length-1,state.index+(a==='next-scene'?1:-1)));state.selected=null;state.time=sceneStart(state.doc,state.index);stopPlayback();renderCanvas();renderTimeline();return}
  if(a==='duplicate-scene'){mutate(()=>{const s=clone(current());s.id=uid();s.name+=' copy';s.layers.forEach(l=>l.id=uid());state.doc.scenes.splice(++state.index,0,s)});return}
  if(a==='delete-scene'){mutate(()=>{state.doc.scenes.splice(state.index,1);if(!state.doc.scenes.length)state.doc.scenes.push(scene());state.index=Math.min(state.index,state.doc.scenes.length-1);state.selected=null});return}
  if(['scene-left','scene-right'].includes(a)){const j=state.index+(a==='scene-left'?-1:1);if(j>=0&&j<state.doc.scenes.length)mutate(()=>{[state.doc.scenes[state.index],state.doc.scenes[j]]=[state.doc.scenes[j],current()];state.index=j});return}
  if(a==='text-add'||a==='shape-add'){mutate(()=>{const l=layer(a==='text-add'?'text':'shape',{duration:current().duration,...(a==='text-add'?{fontSize:+b.dataset.size||64}:{shape:b.dataset.shape||'rectangle',x:25,y:25,w:30,h:30})});current().layers.push(l);state.selected=l.id});state.panel='properties';renderPanel();return}
  if(a==='insert-template'){mutate(()=>{state.doc.scenes.splice(state.index+1,0,applyTemplate(templates[+b.dataset.index]));state.index++;state.selected=null});return}
  if(a==='select-layer'){state.multi=[];state.selected=b.dataset.id;state.panel='properties';renderCanvas();renderPanel();return}
  if(['delete-layer','duplicate-layer','center-x','center-y','layer-up','layer-down','toggle-lock','toggle-hidden'].includes(a)){if(b.dataset.id)state.selected=b.dataset.id;const l=selected();if(!l)return toast('Select a layer first');mutate(()=>{const list=current().layers.includes(l)?current().layers:state.doc.audio;const i=list.indexOf(l);if(a==='delete-layer'){list.splice(i,1);state.selected=null}if(a==='duplicate-layer'){const n=clone(l);n.id=uid();n.x+=2;n.y+=2;list.splice(i+1,0,n);state.selected=n.id}if(a==='center-x')l.x=(100-l.w)/2;if(a==='center-y')l.y=(100-l.h)/2;if(a==='toggle-lock')l.locked=!l.locked;if(a==='toggle-hidden')l.hidden=!l.hidden;if(a==='layer-up'&&i<list.length-1)[list[i],list[i+1]]=[list[i+1],list[i]];if(a==='layer-down'&&i>0)[list[i],list[i-1]]=[list[i-1],list[i]]});renderPanel();return}
  if(a==='animate'){state.panel='properties';renderPanel();return}if(a==='fit'){state.zoom=1;resizeCanvas();return}if(a==='play')return play();
  if(a==='upload'||a==='upload-audio'||a==='upload-avatar'){return chooseFile(a==='upload-audio'?'audio/*':a==='upload-avatar'?'image/*':'image/*,video/*,audio/*',f=>uploadFile(f,a!=='upload-avatar'),a==='upload')}
  if(a==='insert-asset'){const asset=state.assets.find(x=>x.id===b.dataset.id);if(asset)insertAsset(asset);return}
  if(a==='generate'){const model=$('#gen-model').value,prompt=$('#gen-prompt').value,ref=$('#gen-reference').value,duration=+$('#gen-duration')?.value||6,kind=state.panel==='image'?'image':'video';if(!prompt.trim())return toast('Describe what to generate');if(model==='omni-1.1')return queue(`/api/vids/${state.record.id}/generate`,{request_id:uid(),kind:'video',prompt,duration,reference_id:ref||null,aspect:state.doc.aspect==='9:16'?'9:16':'16:9'});return queue('/api/generate',{project_id:pid,request_id:uid(),kind,model:model==='omni-1.1'?'gemini-omni':model,prompt,duration,aspect_ratio:state.doc.aspect,mode:ref?'frames':'text',refs:ref?[state.assets.find(a=>a.id===ref).url]:[],qa:true,audio:true})}
  if(a==='generate-voice'){const text=$('#voice-text').value;if(!text.trim())return toast('Write the spoken text first');mutate(()=>current().notes=text);return queue(`/api/vids/${state.record.id}/generate`,{request_id:uid(),kind:'voice',prompt:text,voice:$('#voice-name').value,language:$('#voice-language').value})}
  if(a==='generate-music')return queue(`/api/vids/${state.record.id}/generate`,{request_id:uid(),kind:'music',prompt:$('#music-prompt').value,duration:+$('#music-duration').value},{music:true});
  if(a==='generate-avatar'){if(!$('#avatar-consent').checked)return toast('Confirm permission to use the likeness and voice');return queue('/api/avatar',{project_id:pid,image_asset_id:$('#avatar-face').value,audio_asset_id:$('#avatar-audio').value,prompt:$('#avatar-prompt').value,consent:$('#avatar-consent').checked,request_id:uid()})}
  if(a==='generate-edit')return queue('/api/ops',{project_id:pid,request_id:uid(),asset_id:$('#edit-asset').value,op:'edit',prompt:$('#edit-prompt').value,qa:true});
  if(a==='generate-captions')return queue(`/api/vids/${state.record.id}/generate`,{request_id:uid(),kind:'captions',asset_id:$('#caption-asset').value},{captions:true,asset_id:$('#caption-asset').value});
  if(a==='import-srt')return chooseFile('.srt',async f=>{const cues=parseSRT(await f.text());if(!cues.length)throw Error('No valid SRT cues found');mutate(()=>current().layers.push(...captionLayers(cues,current().duration)))});
  if(a==='download-srt')return download(state.doc.name+'.srt',toSRT(state.doc),'text/plain');
  if(a==='download-credits'){const urls=new Set([...state.doc.scenes.flatMap(s=>s.layers),...state.doc.audio].map(l=>l.url));const credits=state.assets.filter(a=>urls.has(a.url)&&a.attribution).map(a=>`${a.attribution.title}\n${a.attribution.artist}\n${a.attribution.license}\n${a.attribution.source}`).join('\n\n');return download(state.doc.name+' - credits.txt',credits||'No stock attributions in this video.','text/plain')}
  if(a==='download-json')return download(state.doc.name+'.json',JSON.stringify(state.doc,null,2));
  if(a==='import-document')return chooseFile('.pdf,.pptx,.docx,.txt,.md,.json',async f=>{await save();const data=new FormData();data.append('file',f);toast('Importing document…');const d=await api(`/api/vids/${state.record.id}/import`,{method:'POST',body:data});state.record=d;state.doc=clone(d.document);state.index=0;state.selected=null;state.multi=[];state.undo=[];state.redo=[];renderEditor();toast('Document imported. Add narration from Voiceover.')});
  if(a==='add-comment'){const name=$('#comment-author').value.trim()||'Collaborator';localStorage.setItem('vids-author',name);state.record.comments=await post(`/api/vids/${state.record.id}/comments`,{author:name,text:$('#comment-text').value,scene_id:current().id});renderPanel();return}
  if(a==='resolve-comment'){state.record.comments=await post(`/api/vids/${state.record.id}/comments/${b.dataset.id}/resolve`);renderPanel();return}
  if(a==='restore-version'){await save();const d=await post(`/api/vids/${state.record.id}/restore/${b.dataset.version}`);state.record=d;state.doc=clone(d.document);state.index=0;state.selected=null;renderEditor();toast('Version restored');return}
  if(a==='duplicate-doc'){await save();const d=await post(`/api/vids/${state.record.id}/duplicate`);return openDoc(d.id)}
  if(a==='conflict-copy'){const d=await post(`/api/vids/${state.record.id}/duplicate`,{...state.doc,name:state.doc.name.slice(0,145)+' (my copy)'});state.dirty=false;modal.close();return openDoc(d.id)}
  if(a==='reload'){modal.close();state.dirty=false;return openDoc(state.record.id)}
  if(a==='trash-doc'){await save();await post(`/api/vids/${state.record.id}/trash`);return home()}
  if(a==='share'){await save();showDialog('Share this video',`<p class="panel-note">This link opens the video in your current browser workspace. To share outside this workspace, download the finished video or export the project JSON. Live collaboration across workspaces is not available.</p><input id="share-url" readonly value="${esc(location.href)}" aria-label="Video link">${btn('copy-link','Copy link','copy','full-button primary')}${btn('export','Download a video to share','download','full-button pill')}`);return}
  if(a==='copy-link'){await navigator.clipboard.writeText(location.href);toast('Link copied');return}
  if(a==='export')return showExport();if(a==='render-export'){await save();await queue(`/api/vids/${state.record.id}/export`,{revision:state.record.revision,resolution:$('#export-resolution').value,fps:+$('#export-fps').value,format:$('#export-format').value},{auto:false});modal.close();state.panel='jobs';renderPanel();return}
  if(a==='job-insert'){const j=state.jobs.find(j=>j.id===b.dataset.id);const exportAsset=j.assets.find(a=>['vids-export','vids-production'].includes(a.source));if(exportAsset){showDialog('Your video is ready',`<video controls style="width:100%" src="${esc(exportAsset.url)}"></video><a class="full-button pill primary" href="${esc(exportAsset.url)}" download>Download video</a>`);return}if(j.context?.captions)return insertTranscript(j.assets[0].transcript,current().id);return insertAsset(j.assets[0],j.context||{})}
  if(a==='produce-form'){await save();const narration=state.doc.scenes.reduce((n,s)=>n+(s.notes||s.layers.filter(l=>l.kind==='text').map(l=>l.text).join(' ')).length,0),visuals=state.doc.scenes.filter(s=>!s.layers.some(l=>['image','video'].includes(l.kind))).length;showDialog('Generate a full video',`<p class="panel-note">Generate missing visuals, narrate scripts with a consistent voice, create a shared soundtrack, and render an MP4 using your Connections. Review the generated scenes before replacing your edit.</p><div class="chip">Billed by your chosen providers. Each enabled step submits paid requests.</div><label>Voice<select id="produce-voice">${state.config.voices.map(v=>`<option>${esc(v)}</option>`).join('')}</select></label><label class="inline"><input type="checkbox" id="produce-visuals" ${state.config.capabilities?.image?'checked':'disabled'}>Generate missing visuals</label><label class="inline"><input type="checkbox" id="produce-narration" ${state.config.capabilities?.voice?'checked':'disabled'}>Narrate scene scripts</label><label class="inline"><input type="checkbox" id="produce-music" ${state.config.capabilities?.music?'checked':'disabled'}>Create a shared soundtrack</label><textarea id="produce-music-prompt" aria-label="Soundtrack direction">Gentle hopeful instrumental piano, no vocals, subtle background soundtrack.</textarea>${btn('produce','Generate and render','spark','full-button primary')}`);return}
  if(a==='produce'){await queue(`/api/vids/${state.record.id}/produce`,{revision:state.record.revision,request_id:uid(),voice:$('#produce-voice').value,visuals:$('#produce-visuals').checked,narration:$('#produce-narration').checked,music:$('#produce-music').checked,music_prompt:$('#produce-music-prompt').value},{auto:false});modal.close();state.panel='jobs';renderPanel();return}
  if(a==='apply-production'){const job=state.jobs.find(j=>j.id===b.dataset.id);if(job.vids_base_revision!==state.record.revision||state.dirty)return toast('This video changed while generating. The generated media is in Uploads; keep your current edits or create a new draft.');mutate(()=>{state.doc=clone(job.vids_proposal);state.index=0;state.selected=null;state.multi=[]});await save();job.context={...job.context,applied:true};localStorage.setItem('vids-jobs-'+state.record.id,JSON.stringify(state.jobs));renderEditor();toast('Generated scenes applied');return}
  if(a==='assistant-plan'){await save();const prompt=$('#assistant-prompt').value;$('#assistant-result').innerHTML='<p class="panel-note">Drafting your changes…</p>';const proposal=await post(`/api/vids/${state.record.id}/plan`,{prompt});proposedDoc=proposal;$('#assistant-result').innerHTML=`<div class="chip">${proposal.document.scenes.length} scenes · ${total(proposal.document)} seconds</div>${proposal.document.scenes.map(s=>`<div class="comment"><strong>${esc(s.name)}</strong><p>${esc(s.notes||s.layers.filter(l=>l.kind==='text').map(l=>l.text).join(' '))}</p><small>${s.duration} seconds</small></div>`).join('')}${btn('apply-plan','Apply changes','check','full-button primary')}`;return}
  if(a==='apply-plan'){if(!proposedDoc)return;if(proposedDoc.base_revision!==state.record.revision)return toast('Your video changed since this draft. Ask for a new draft.');mutate(()=>{state.doc=clone(proposedDoc.document);state.index=0;state.selected=null});proposedDoc=null;renderPanel();return}
  if(a==='record-start')return startRecording();if(a==='record-stop'){recording?.rec.stop();return}
  if(['stock-search','stock-next','stock-prev','stock-insert'].includes(a))return stockPanel.action(a,b);

  if(a==='shortcuts')return showDialog('Keyboard shortcuts','<p>Space — play / pause</p><p>⌘ / Ctrl Z — undo</p><p>⌘ / Ctrl Shift Z — redo</p><p>⌘ / Ctrl D — duplicate layer</p><p>Delete — remove selected layer</p><p>Arrow keys — move layer (Shift for larger steps)</p>');
  if(a==='about')return showDialog('OpenVid','<p class="panel-note">OpenVid is a standalone open-source scene editor with bring-your-own-provider connections and HyperFrames export. Keys are encrypted on your server. Code is licensed under AGPL-3.0; bundled media has separate asset terms.</p><a href="https://github.com/hanishkeloth/OpenVid" target="_blank" rel="noopener">Source code and licence</a>');
}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!e.target.closest('.menu-pop')&&!b?.matches('[data-action="menu"]'))$('.menu-pop')?.remove();if(!b)return;const a=b.dataset.action;if(a!=='menu')$('.menu-pop')?.remove();if(b.disabled)return;const costly=['produce','generate','generate-voice','generate-music','generate-avatar','generate-edit','generate-captions','render-export','assistant-plan','voice-clone-submit','voice-save-library','voice-design-submit','voice-save-sample-submit','profile-generate'];try{if(costly.includes(a))b.disabled=true;await action(a,b)}catch(e){error(e)}finally{if(costly.includes(a)&&b.isConnected)b.disabled=false}});
document.addEventListener('input',e=>{if(e.target.id==='library-search')renderLibrary();if(e.target.id==='asset-search')$('#asset-grid').innerHTML=assetCards(state.assets.filter(a=>(a.prompt||'').toLowerCase().includes(e.target.value.toLowerCase())));if(e.target.id==='playhead'){state.time=+e.target.value;const p=$('hyperframes-player');if(p)p.seek(state.time);else{state.index=Math.max(0,state.doc.scenes.findIndex((s,i)=>state.time<sceneStart(state.doc,i)+s.duration));if(state.time>=total(state.doc))state.index=state.doc.scenes.length-1;state.selected=null;renderCanvas();renderTimeline()}$('#time-label').textContent=`${format(state.time)} / ${format(total(state.doc))}`}});
document.addEventListener('change',e=>{const el=e.target;try{if(el.id==='library-filter'){state.filter=el.value;renderLibrary()}if(el.id==='doc-name')mutate(()=>{state.doc.name=el.value||'Untitled video';document.title=state.doc.name+' – OpenVid'});if(el.id==='captions-visible')mutate(()=>state.doc.captions=el.checked);if(el.dataset.field){const key=el.dataset.field;const value=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value;if(el.type==='number'&&!Number.isFinite(value))return;mutate(()=>{if(key.startsWith('scene.'))current()[key.slice(6)]=value;else if(key.startsWith('doc.'))state.doc[key.slice(4)]=value;else if(selected())selected()[key]=value})}}catch(e){error(e)}});
document.addEventListener('dblclick',e=>{const n=e.target.closest('[data-layer]');if(!n)return;const l=current().layers.find(l=>l.id===n.dataset.layer);if(l.kind!=='text'||l.locked)return;state.selected=l.id;state.panel='properties';renderPanel();const input=document.querySelector('[data-field="text"]');input?.focus();input?.select()});
document.addEventListener('pointerdown',e=>{const n=e.target.closest('[data-layer]');if(!n||state.playing)return;if(e.button!==0)return;const l=current().layers.find(l=>l.id===n.dataset.layer);if(e.shiftKey){const ids=new Set(state.multi||[state.selected].filter(Boolean));ids.has(l.id)?ids.delete(l.id):ids.add(l.id);state.multi=[...ids];state.selected=state.multi.at(-1);renderCanvas();return}if(l.group)state.multi=current().layers.filter(x=>x.group===l.group).map(x=>x.id);else if(!(state.multi||[]).includes(l.id))state.multi=[l.id];state.selected=l.id;document.querySelectorAll('.canvas-layer').forEach(x=>x.classList.toggle('selected',(state.multi||[]).includes(x.dataset.layer)));if(l.locked){renderPanel();return}e.preventDefault();const resize=e.target.dataset.resize,rect=$('#canvas-shell').getBoundingClientRect(),sx=e.clientX,sy=e.clientY,orig={x:l.x,y:l.y,w:l.w,h:l.h},group=extras.selection().filter(x=>!x.locked).map(x=>({l:x,x:x.x,y:x.y}));let moved=false;const move=ev=>{if(!moved){checkpoint();moved=true}const dx=(ev.clientX-sx)/rect.width*100,dy=(ev.clientY-sy)/rect.height*100;if(resize){l.w=Math.max(1,orig.w+dx);l.h=Math.max(1,orig.h+dy)}else{for(const g of group){const snap=localStorage.getItem('vids-snap')!=='false';g.l.x=snap?Math.round(g.x+dx):g.x+dx;g.l.y=snap?Math.round(g.y+dy):g.y+dy;const el=document.querySelector(`[data-layer="${g.l.id}"]`);if(el){el.style.left=g.l.x+'%';el.style.top=g.l.y+'%'}}}n.style.left=l.x+'%';n.style.top=l.y+'%';n.style.width=l.w+'%';n.style.height=l.h+'%'};const up=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up);if(moved)changed();else renderCanvas();if(state.panel==='properties')renderPanel()};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up)});
let dragIndex=null;document.addEventListener('dragstart',e=>{const n=e.target.closest('[data-scene-index]');if(n){dragIndex=+n.dataset.sceneIndex;e.dataTransfer.effectAllowed='move'}});document.addEventListener('dragover',e=>{if(e.target.closest('[data-scene-index]'))e.preventDefault()});document.addEventListener('drop',e=>{const n=e.target.closest('[data-scene-index]');if(!n||dragIndex===null)return;e.preventDefault();const at=+n.dataset.sceneIndex;mutate(()=>{const [s]=state.doc.scenes.splice(dragIndex,1);state.doc.scenes.splice(at,0,s);state.index=at});dragIndex=null});
document.addEventListener('keydown',e=>{if(!state.doc||modal.open||e.target.matches('input,textarea,select,[contenteditable]'))return;const command=e.metaKey||e.ctrlKey;let a;if(command&&e.key.toLowerCase()==='z')a=e.shiftKey?'redo':'undo';else if(command&&e.key.toLowerCase()==='c')a='copy-layer';else if(command&&e.key.toLowerCase()==='x')a='cut-layer';else if(command&&e.key.toLowerCase()==='v')a='paste-layer';else if(command&&e.key.toLowerCase()==='a')a='select-all';else if(command&&e.shiftKey&&e.key.toLowerCase()==='s')a='split-scene';else if(command&&e.key.toLowerCase()==='d')a='duplicate-layer';else if(e.key==='Delete'||e.key==='Backspace')a='delete-layer';else if(e.code==='Space')a='play';if(a){e.preventDefault();action(a,{dataset:{}}).catch(error)}if(e.key.startsWith('Arrow')&&selected()){e.preventDefault();const l=selected(),delta=e.shiftKey?1:.1;mutate(()=>{if(e.key==='ArrowLeft')l.x-=delta;if(e.key==='ArrowRight')l.x+=delta;if(e.key==='ArrowUp')l.y-=delta;if(e.key==='ArrowDown')l.y+=delta})}});
window.addEventListener('beforeunload',e=>{if(state.dirty||recording){e.preventDefault();e.returnValue=''}});
window.addEventListener('popstate',()=>init().catch(error));
const extras=editorExtras({state,$,btn,mutate,current,selected,toast,renderCanvas,renderTimeline,renderPanel,showDialog,api,post,queue,stopPlayback,resizeCanvas});
Object.assign(extras.actions,voiceWorkspace({state,$,btn,api,post,queue,showDialog,toast,current}));
init().catch(error);
