import {esc} from './vids-core.js';

export function voiceWorkspace({state,$,btn,api,post,queue,showDialog,toast,current}) {
  let profiles=[],catalog=[],voiceConfig={languages:[]},page=0,query='';
  const pid=()=>state.record.project_id;
  const languages=()=>`<option value="">Auto detect</option>${voiceConfig.languages.map(l=>`<option value="${esc(l.language_id)}">${esc(l.name)}</option>`).join('')}`;
  const cards=()=>profiles.map(v=>`<div class="comment"><strong>${esc(v.name)}</strong><p>${esc(v.description||v.origin)}</p>${v.preview_url?`<audio class="voice-sample" controls src="${esc(v.preview_url)}"></audio>`:''}${btn('profile-speak','Use for this scene',null,'pill',`data-id="${v.id}"`)}${v.requires_verification?'<p>Complete voice verification in your ElevenLabs account before generating speech.</p>':''}</div>`).join('');
  const actions={
    'voice-library':async()=>{
      showDialog('Voice library','<p>Loading saved voices…</p>');
      profiles=(await api(`/api/projects/${pid()}/voices`)).voices;
      let message='';try{voiceConfig=await api('/api/voices/config')}catch(e){message=e.message}
      showDialog('Voice library',`<p class="panel-note">Custom voices use your connected ElevenLabs account with Eleven v3. Fal preset voices remain available in Voiceover.</p>${message?`<p class="panel-note">${esc(message)}</p>`:''}<div class="row">${btn('voice-browse','Browse',null,'pill')}${btn('voice-design-form','Design a voice',null,'pill')}${btn('voice-clone-form','Clone voice',null,'pill')}</div>${cards()||'<p>No saved voices yet.</p>'}`);
    },
    'voice-browse':async()=>{showDialog('Browse ElevenLabs voices',`<input id="voice-search" placeholder="Search voices" aria-label="Search voices" value="${esc(query)}"><label>Language<select id="voice-filter">${languages()}</select></label>${btn('voice-search','Search',null,'full-button primary')}<div id="voice-results"></div>`);await search(false)},
    'voice-search':()=>search(false),
    'voice-next':()=>search(true),
    'voice-save-library':async b=>{const v=catalog[+b.dataset.index];await post('/api/voices/save',{project_id:pid(),name:v.name,description:v.description,provider_voice_id:v.id,public_owner_id:v.public_owner_id,language_code:$('#voice-filter').value||null});toast('Voice saved');await actions['voice-library']()},
    'voice-clone-form':()=>showDialog('Clone your voice',`<p class="panel-note">Choose 10 seconds to 10 minutes of clear speech. The selected recordings are sent to your ElevenLabs account. Use your own voice or a voice you have permission to clone.</p><label>Name<input id="clone-name"></label><label>Language<select id="clone-language">${languages()}</select></label>${state.assets.filter(a=>['audio','video'].includes(a.kind)).map(a=>`<label class="inline"><input type="checkbox" name="clone-sample" value="${a.id}">${esc((a.prompt||a.kind).slice(0,90))}</label>`).join('')||'<p>Upload or record speech first.</p>'}<label class="inline"><input id="clone-consent" type="checkbox">This is my voice, or I have permission to clone it.</label><label class="inline"><input id="clone-clean" type="checkbox">Remove background noise</label>${btn('voice-clone-submit','Create voice clone',null,'full-button primary')}`),
    'voice-clone-submit':async()=>{const samples=[...document.querySelectorAll('[name="clone-sample"]:checked')].map(el=>el.value);if(!$('#clone-consent').checked)return toast('Confirm permission to clone the voice');await post('/api/voices/clone',{project_id:pid(),name:$('#clone-name').value,asset_ids:samples,consent:true,remove_background_noise:$('#clone-clean').checked,language_code:$('#clone-language').value||null});toast('Voice clone saved');await actions['voice-library']()},
    'voice-design-form':()=>showDialog('Design a voice',`<p class="panel-note">Describe the age, accent, tone, and delivery. Eleven v3 creates audition samples in your media library.</p><textarea id="design-description" placeholder="A warm, calm adult storyteller with a gentle Indian English accent…"></textarea><textarea id="design-text" placeholder="Write at least 100 characters of sample dialogue…">Every story begins with a small idea. Let us bring it to life together, one scene at a time, with a voice that feels natural and familiar.</textarea>${btn('voice-design-submit','Generate audition samples',null,'full-button primary')}${state.assets.filter(a=>a.source==='voice-design').map(a=>`<div class="comment"><audio class="voice-sample" controls src="${esc(a.url)}"></audio>${btn('voice-save-sample','Save this voice',null,'pill',`data-id="${a.id}"`)}</div>`).join('')}`),
    'voice-design-submit':async()=>{await queue('/api/voices/design',{project_id:pid(),description:$('#design-description').value,text:$('#design-text').value},{auto:false});$('#modal').close();toast('Voice auditions are generating. Open Design a voice again when complete.')},
    'voice-save-sample':b=>showDialog('Name this voice',`<input id="voice-sample-name" placeholder="Voice name"><button class="full-button primary" data-action="voice-save-sample-submit" data-id="${b.dataset.id}">Save voice</button>`),
    'voice-save-sample-submit':async b=>{await post('/api/voices/save',{project_id:pid(),name:$('#voice-sample-name').value,preview_asset_id:b.dataset.id});await actions['voice-library']()},
    'profile-speak':b=>{const v=profiles.find(v=>v.id===b.dataset.id);showDialog(`Narration · ${esc(v.name)}`,`<textarea id="profile-script" aria-label="Saved voice narration">${esc(current().notes)}</textarea><button data-action="profile-generate" data-id="${v.id}" class="full-button primary">Generate Eleven v3 narration</button>`)},
    'profile-generate':async b=>{await queue('/api/audio',{project_id:pid(),kind:'voice',prompt:$('#profile-script').value,voice_profile_id:b.dataset.id});$('#modal').close()},
  };
  async function search(next){query=$('#voice-search').value;page=next?page+1:0;const result=await api(`/api/voices/library?search=${encodeURIComponent(query)}&language=${encodeURIComponent($('#voice-filter').value)}&page=${page}`);catalog=result.voices;$('#voice-results').innerHTML=catalog.map((v,i)=>`<div class="comment"><strong>${esc(v.name)}</strong><p>${esc(v.description)}</p>${v.preview_url?`<audio class="voice-sample" controls src="${esc(v.preview_url)}"></audio>`:''}${btn('voice-save-library','Save to this video',null,'pill',`data-index="${i}"`)}</div>`).join('')+(result.next_page!==null?btn('voice-next','Next page',null,'full-button pill'):'')}
  return actions;
}
