import {uid,esc,clone,total,sceneStart,splitScene,clipLayerRange} from './vids-core.js';

export function editorExtras(ctx) {
  const {state,$,btn,mutate,current,selected,toast,renderCanvas,renderTimeline,renderPanel,showDialog,api,post,queue}=ctx;
  let clipboard=[];
  const refresh=()=>{renderCanvas();renderTimeline();renderPanel()};
  const selection=()=>current().layers.filter(l=>(state.multi||[]).includes(l.id)||l.id===state.selected);
  const styles=[['Sage','#e1eadd','#243d32','#769980','Georgia'],['Studio','#20283d','#ffffff','#8babff','Arial'],['Warm','#f5e6ca','#3e3324','#be7859','Trebuchet MS'],['Lilac','#e2e1f2','#373551','#8b7ec6','Arial'],['Paper','#ffffff','#202124','#4285f4','Arial']];
  const actions={
    'styles':()=>{state.panel='styles';renderPanel()},
    'apply-style':b=>mutate(()=>{const t=styles[+b.dataset.index];for(const s of ($('#style-scope').value==='all'?state.doc.scenes:[current()])){s.background=t[1];for(const l of s.layers){if(l.kind==='text'&&!l.caption){l.color=t[2];l.font=t[4]}if(l.kind==='shape')l.fill=t[3]}}}),
    'storyboard':()=>{state.panel='storyboard';renderPanel()},
    'transcript':()=>{state.panel='transcript';renderPanel()},
    'split-scene':()=>{const t=state.time-sceneStart(state.doc,state.index);const parts=splitScene(current(),t);mutate(()=>{state.doc.scenes.splice(state.index,1,...parts);state.index++;state.selected=null;state.multi=[]});refresh()},
    'split-layer':()=>{const l=selected();if(!l)return toast('Select a timed layer first');const list=current().layers.includes(l)?current().layers:state.doc.audio;const t=state.time-(list===state.doc.audio?0:sceneStart(state.doc,state.index));if(t<=l.start+.05||t>=l.start+l.duration-.05)return toast('Put the playhead inside the selected layer');const a=clipLayerRange(l,0,t),b=clipLayerRange(l,t,l.start+l.duration);b.start+=t;mutate(()=>list.splice(list.indexOf(l),1,a,b));refresh()},
    'copy-layer':()=>{clipboard=clone(selection());toast(`${clipboard.length} layer(s) copied`)},
    'cut-layer':()=>{clipboard=clone(selection());actions['delete-layer']()},
    'paste-layer':()=>{if(!clipboard.length)return toast('Copy a layer first');mutate(()=>{const groups=new Map();state.multi=clipboard.map(l=>{const n={...clone(l),id:uid(),x:l.x+2,y:l.y+2};if(l.group){if(!groups.has(l.group))groups.set(l.group,uid());n.group=groups.get(l.group)}current().layers.push(n);return n.id});state.selected=state.multi.at(-1)});refresh()},
    'duplicate-layer':()=>{const l=selected();if(l&&state.doc.audio.includes(l)){mutate(()=>{const n={...clone(l),id:uid()};state.doc.audio.push(n);state.selected=n.id});return}const previous=clipboard;clipboard=clone(selection());actions['paste-layer']();clipboard=previous},
    'select-all':()=>{state.multi=current().layers.filter(l=>!l.locked).map(l=>l.id);state.selected=state.multi.at(-1);refresh()},
    'delete-layer':b=>{if(b?.dataset.id){state.selected=b.dataset.id;state.multi=[]}const ids=selection().filter(l=>!l.locked).map(l=>l.id);const audio=state.doc.audio.find(l=>l.id===state.selected&&!l.locked);if(!ids.length&&!audio)return toast('Select an unlocked layer first');mutate(()=>{current().layers=current().layers.filter(l=>!ids.includes(l.id));if(audio)state.doc.audio=state.doc.audio.filter(l=>l!==audio);state.multi=[];state.selected=null});refresh()},
    'group':()=>{const list=selection();if(list.length<2)return toast('Shift-click two or more layers to group');mutate(()=>{const id=uid();list.forEach(l=>l.group=id)});toast('Layers grouped')},
    'ungroup':()=>mutate(()=>selection().forEach(l=>l.group='')),
    'flip-x':()=>mutate(()=>selection().filter(l=>!l.locked).forEach(l=>l.flipX=!l.flipX)),
    'flip-y':()=>mutate(()=>selection().filter(l=>!l.locked).forEach(l=>l.flipY=!l.flipY)),
    'rotate-right':()=>mutate(()=>selection().filter(l=>!l.locked).forEach(l=>l.rotation=((l.rotation||0)+90)%360)),
    'front':()=>mutate(()=>{const list=selection();current().layers=current().layers.filter(l=>!list.includes(l)).concat(list)}),
    'back':()=>mutate(()=>{const list=selection();current().layers=list.concat(current().layers.filter(l=>!list.includes(l)))}),
    'find':()=>showDialog('Find and replace',`<label>Find<input id="find-text" aria-label="Find text"></label><label>Replace with<input id="replace-text" aria-label="Replace with"></label><label class="inline"><input id="find-case" type="checkbox">Match case</label>${btn('replace-all','Replace all',null,'full-button primary')}<p id="find-result" role="status"></p>`),
    'replace-all':()=>{const needle=$('#find-text').value;if(!needle)return;const replacement=$('#replace-text').value,sensitive=$('#find-case').checked;let count=0;const replace=text=>text.replace(new RegExp(needle.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),sensitive?'g':'gi'),()=>{count++;return replacement});mutate(()=>{for(const s of state.doc.scenes){s.notes=replace(s.notes);for(const l of s.layers)if(l.kind==='text')l.text=replace(l.text)}});$('#find-result').textContent=`Replaced ${count} occurrence(s).`},
    'zoom':()=>showDialog('Canvas and timeline zoom',`<label>Canvas<select id="canvas-zoom">${[[.5,'50% of fit'],[1,'Fit'],[1.5,'150% of fit'],[2,'200% of fit']].map(([v,n])=>`<option value="${v}" ${state.zoom===v?'selected':''}>${n}</option>`).join('')}</select></label><label>Timeline<select id="timeline-zoom">${[.5,1,1.5,2].map(v=>`<option value="${v}" ${(state.timelineZoom||1)===v?'selected':''}>${v*100}%</option>`).join('')}</select></label>`),
    'full-screen':async()=>{if(document.fullscreenElement)await document.exitFullscreen();else await $('#app').requestFullscreen()},
    'timing':()=>{state.showTiming=!state.showTiming;renderTimeline()},
    'preferences':()=>showDialog('Preferences',`<label class="inline"><input id="pref-snap" type="checkbox" ${localStorage.getItem('vids-snap')!=='false'?'checked':''}>Snap positions to a 1% grid</label><p class="panel-note">Use Shift-click to select several layers. Text fields use the browser’s spelling suggestions. Keyboard controls and labels are available throughout the editor.</p>`),
    'script-save':()=>{const fields=[...document.querySelectorAll('[data-script-id]')];mutate(()=>{for(const f of fields)state.doc.scenes.find(s=>s.id===f.dataset.scriptId).notes=f.value});toast('Scripts saved')},
    'paint-copy':()=>{const l=selected();if(!l)return toast('Select a formatted layer first');state.paint=Object.fromEntries(['color','fill','font','fontSize','bold','italic','align','opacity','radius','borderWidth','borderColor','shadow'].map(k=>[k,l[k]]));toast('Style copied. Select another layer, then Apply copied style.')},
    'paint-apply':()=>{if(!state.paint||!selected())return toast('Copy a style and select a layer first');mutate(()=>Object.assign(selected(),state.paint));refresh()},
  };
  for(const edge of ['left','right','top','bottom','horizontal','vertical'])actions['align-'+edge]=()=>{const list=selection();if(!list.length)return;const x=Math.min(...list.map(l=>l.x)),y=Math.min(...list.map(l=>l.y)),r=Math.max(...list.map(l=>l.x+l.w)),b=Math.max(...list.map(l=>l.y+l.h));mutate(()=>{for(const l of list){if(l.locked)continue;if(edge==='left')l.x=x;if(edge==='right')l.x=r-l.w;if(edge==='top')l.y=y;if(edge==='bottom')l.y=b-l.h;if(edge==='horizontal')l.x=(x+r-l.w)/2;if(edge==='vertical')l.y=(y+b-l.h)/2}})};
  for(const axis of ['x','y'])actions['distribute-'+axis]=()=>{const list=selection().filter(l=>!l.locked).sort((a,b)=>a[axis]-b[axis]);if(list.length<3)return toast('Select at least three layers');const size=axis==='x'?'w':'h',start=list[0][axis],end=list.at(-1)[axis]+list.at(-1)[size],gap=(end-start-list.reduce((n,l)=>n+l[size],0))/(list.length-1);mutate(()=>{let pos=start;for(const l of list){l[axis]=pos;pos+=l[size]+gap}})};
  const panels={
    styles:()=>`<p class="panel-note">Set a consistent color palette and typography.</p><label>Apply to<select id="style-scope"><option value="all">All scenes</option><option value="scene">Current scene</option></select></label>${styles.map((t,i)=>`<button class="template-card" data-action="apply-style" data-index="${i}" style="background:${t[1]};color:${t[2]};font-family:${t[4]}">${t[0]}<small>A fresh perspective.</small></button>`).join('')}`,
    storyboard:()=>`<p class="panel-note">Review the sequence and edit each scene’s script.</p>${state.doc.scenes.map((s,i)=>`<div class="comment"><button data-action="select-scene" data-index="${i}"><strong>${i+1}. ${esc(s.name)} · ${s.duration}s</strong></button><textarea data-script-id="${s.id}" aria-label="Script for scene ${i+1}">${esc(s.notes)}</textarea></div>`).join('')}${btn('script-save','Save scripts',null,'full-button primary')}`,
    transcript:()=>state.doc.scenes.map((s,i)=>`<div class="comment"><button data-action="select-scene" data-index="${i}"><strong>${esc(s.name)}</strong></button>${s.layers.filter(l=>l.caption).sort((a,b)=>a.start-b.start).map(l=>`<button class="transcript-cue" data-action="seek-cue" data-time="${sceneStart(state.doc,i)+l.start}" data-index="${i}">${(sceneStart(state.doc,i)+l.start).toFixed(1)}s · ${esc(l.text)}</button>`).join('')||`<p>${esc(s.notes||'No transcript yet. Generate captions from this scene’s audio.')}</p>`}</div>`).join(''),
  };
  actions['seek-cue']=b=>{state.index=+b.dataset.index;state.time=+b.dataset.time;ctx.stopPlayback();renderCanvas();renderTimeline()};
  document.addEventListener('change',e=>{if(e.target.id==='canvas-zoom'){state.zoom=+e.target.value;ctx.resizeCanvas()}if(e.target.id==='timeline-zoom'){state.timelineZoom=+e.target.value;renderTimeline()}if(e.target.id==='pref-snap')localStorage.setItem('vids-snap',String(e.target.checked))});
  function timeline(){
    const z=state.timelineZoom||1;document.querySelectorAll('.scene-card').forEach(n=>n.style.flexBasis=150*z+'px');
    const tracks=$('#trackbar');if(!tracks)return;
    tracks.classList.toggle('detailed',!!state.showTiming);if(!state.showTiming)return;
    tracks.innerHTML=[...current().layers,...state.doc.audio].map(l=>{const length=state.doc.audio.includes(l)?total(state.doc):current().duration;return `<div class="timing-row"><button data-action="select-layer" data-id="${l.id}" title="${esc(l.text||l.kind)}">${esc((l.text||l.kind).slice(0,16))}</button><div class="timing-lane" data-length="${length}"><div class="timing-bar ${l.id===state.selected?'active':''}" data-timing="${l.id}" style="left:${l.start/length*100}%;width:${Math.max(0,Math.min(l.duration,length-l.start))/length*100}%" title="${l.start.toFixed(1)}–${(l.start+l.duration).toFixed(1)} seconds"><span data-edge="left"></span>${l.duration.toFixed(1)}s<span data-edge="right"></span></div></div></div>`}).join('');
  }
  document.addEventListener('pointerdown',e=>{const n=e.target.closest('[data-timing]');if(!n)return;const l=[...current().layers,...state.doc.audio].find(l=>l.id===n.dataset.timing);if(l.locked)return;const edge=e.target.dataset.edge,rect=n.parentElement.getBoundingClientRect(),length=+n.parentElement.dataset.length,x=e.clientX,original=clone(l);let next=clone(l);e.preventDefault();const move=ev=>{const d=(ev.clientX-x)/rect.width*length;next=clone(original);if(edge==='right')next.duration=Math.max(.05,Math.min(length-original.start,original.duration+d));else if(edge==='left'){const start=Math.max(0,Math.min(original.start+original.duration-.05,original.start+d));next.start=start;next.duration=original.start+original.duration-start;if(['audio','video'].includes(l.kind)){next.trim=Math.max(0,original.trim+(start-original.start)*original.speed)}}else next.start=Math.max(0,Math.min(length-original.duration,original.start+d));n.style.left=next.start/length*100+'%';n.style.width=next.duration/length*100+'%'};const up=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up);mutate(()=>Object.assign(l,next));renderPanel()};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up)});
  return {actions,panels,timeline,selection};
}
